services:
  - type: web
    name: rag-api-service
    runtime: python

    # Build & start commands
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    # Source repository
    repo: https://github.com/AtharvaBagade23/RAG_Python_Service.git
    branch: main

    # Environment variables
    envVars:
      - key: PORT
        value: 8000

    # Auto-deploy on git push
    autoDeploy: true

    # Instance type
    plan: starter

    # Health check
    healthCheckPath: /
